name: "continuous_integration"
on:
  push:
    branches: [ master ]

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Set Up Python 3.8
	uses: actions/setup-python@v2
	with: 
	  python-version: 3.8
      - name: Install dependecies
	run: |
	  python -m pip install --upgrade pip # this will install pip3 because the action only installs python
	  if [ -f requirements.txt]; then pip install -r requirements.txt; fi #this will only run if requirements.txt exists, it's a bash command for if
      - name: Run Tests
	run: |
 	  python -m unittest discover tests/ # run tests from the tests directory
