name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Set Up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Tests
        run: |
          python -m unittest discover tests/

  deployment: 
    needs: test_suite # this job cannot run unless test_suite, the previous job, is done and passes
    runs-on: ubuntu-latest
    steps:
      - name: Fresh Clone & Repo Install
        uses: appleboy/ssh-action@master
        with: 
          host: 54.204.119.138
          username: github-action
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            rm -rf squiz
            git clone https://github.com/yaraya24/squiz.git
            python3.8 -m venv /home/github-action/squiz/venv
            source /home/github-action/squiz/venv/bin/activate
            pip install -r /home/github-action/squiz/requirements.txt
